name: backend CD

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/mysports
            . venv/bin/activate
            cd backend
            git pull
            git checkout nightly
            git pull
            pip install -r requirements.txt
            sudo supervisorctl restart MySports

