name: test

on:
  push:
    branches:
      - nightly

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pre run backend
        run: |
          pip install -r requirements.txt
          python run.py
      